export const cdb="cdb-L1"
export const financials="financials-db"
export const heimdall="heimdall-db"
export const aicite="AICITE-IC"
export const aka_search="AKA_Search"
export const patent="patent"
export const aicite_ic= "AICITE-IC"
export const business_news ="Business-News"
export const cap_tables = "cap-tables"
export const heimdall_v2="heimdall-v2"
export const incite_user="Incite-User"
export const aicite_user= "Aicite-User"
export const trending= "Trending-News"
export const all_sector = "All-Sectors"

